README.md
components/admin.js
components/auth.js
components/envelopes.js
components/folders.js
components/users.js
docusign.js
dsUtils.js
package.json
test/component tests/admin.js
test/component tests/envelopes.js
test/component tests/folders.js
test/component tests/users.js
test/walkthrough tests/embedded_docusign_console.js
test/walkthrough tests/embedded_sending.js
test/walkthrough tests/embedded_signing.js
test/walkthrough tests/get_doc_list_download_docs.js
test/walkthrough tests/get_envelope_info.js
test/walkthrough tests/get_envelope_recipient_status.js
test/walkthrough tests/get_status_envelopes.js
test/walkthrough tests/request_signature_on_document.js
test/walkthrough tests/request_signature_template.js

Fix #7 
This is the [semistandard](https://www.npmjs.com/package/semistandard) style which is based on [standard](https://www.npmjs.com/package/standard) but adds semicolons

Semi standard style

---

README.md
components/admin.js
components/auth.js
components/envelopes.js
components/folders.js
components/users.js
docusign.js
dsUtils.js
package.json
test/component tests/admin.js
test/component tests/envelopes.js
test/component tests/folders.js
test/component tests/users.js
test/walkthrough tests/embedded_docusign_console.js
test/walkthrough tests/embedded_sending.js
test/walkthrough tests/embedded_signing.js
test/walkthrough tests/get_doc_list_download_docs.js
test/walkthrough tests/get_envelope_info.js
test/walkthrough tests/get_envelope_recipient_status.js
test/walkthrough tests/get_status_envelopes.js
test/walkthrough tests/request_signature_on_document.js
test/walkthrough tests/request_signature_template.js

Fix #6 
This is still missing updates to the tests, which I'm currently in the process of working on.
Wanted to get some early feedback from you guys about this while I'm doing that

Normalize error passing

---

components/envelopes.js

Expose the authentication method property for embedded signing, also enforce required parameters

expose auth method, enforce required params

---

components/envelopes.js
package.json

Support all envelope opts

---

components/envelopes.js
docusign.js

Version 4.0 is broken. Please merge and republish.

Fix syntax and linting errors

---

examples/auth-store-helpers.js
examples/stored-auth.js

create example of how to store and use authInfo

---

README.md
package.json

NPM package version bumped to 3.2.1

Updated superagent version

---

README.md

Changed ordering of variables and some comments to be easier to understand without reading the authentication guide. I also removed some unused variables to prevent confusion when implementing the example.

Updated OAuth JWT Grant Example

---

.gitignore
CHANGELOG.md
README.md
package.json

- Added support for version v2.1-20.2.00 of the DocuSign eSignature API.
- Added properties `batchSize`, `queueLimit`, and `totalQueued` to bulk send response.

Version 5.5.0 release

---

.gitignore
.swagger-codegen-ignore
CHANGELOG.md
README.md
package.json

- Added support for version v2-20.2.00 of the DocuSign eSignature API.
- Updated/added properties for bulk update call

Version 4.8.0 release

---

package.json
src/api/BulkEnvelopesApi.js
src/model/NewUser.js
src/model/SenderEmailNotifications.js
src/model/TabMetadata.js

- Added support for version v2-20.2.02.02 of the DocuSign eSignature API.

SDK Version 4.9.0-rc1

---

package.json
src/api/EnvelopesApi.js
src/model/CorrectViewRequest.js
src/model/UserAccountManagementGranularInformation.js

- Added support for version v2-20.3.00 of the DocuSign eSignature API.

Version 4.10.0-rc1 release

---

CHANGELOG.md
package.json

- Added support for version v2-20.3.00 of the DocuSign eSignature API.

Version 4.10.0 release

---

CHANGELOG.md
package.json

- Added support for version v2.1-20.3.00 of the DocuSign eSignature API.

Version 5.7.0 release

---

CHANGELOG.md
package.json
src/ApiClient.js
src/api/AccountsApi.js
test/SdkUnitTests.js
test/SdkUnitTestsWithCallback.js
test/docs/brand.xml

- Added support for version v2-20.3.01 of the DocuSign eSignature API.

Version 4.10.1 release

---

CHANGELOG.md
package.json
src/ApiClient.js
src/api/AccountsApi.js
test/SdkUnitTests.js
test/SdkUnitTestsWithCallback.js
test/docs/brand.xml

- Added support for version v2.1-20.3.01 of the DocuSign eSignature API.
- DCM-3866, Added support for updateBrandResourcesByContentType function to take in file to upload.
- DCM-3369, Updated ApiClient to use an empty JSON object if the body is null.
- DCM-4614, Fixed out of memory issue when deserializing large files.

Version 5.8.1 release

---

CHANGELOG.md
README.md
package.json
src/api/EnvelopesApi.js

- Added support for version v2-21.1.01.03 of the DocuSign eSignature API.

Version 4.11.0 release

---

CHANGELOG.md
package.json

- Added support for version v2-21.2.00.00 of the DocuSign eSignature API.

Version 4.13.0 release

---

CHANGELOG.md
package.json

- Added support for version v2.1-21.2.00.00 of the DocuSign eSignature API.

Version 5.11.0 release

---

CHANGELOG.md
README.md
package.json
test/SdkUnitTests.js

- Updated Get Form Data unit test
- Updated Travis-CI badge in README.md

Version 5.11.1 release

---

CHANGELOG.md
README.md
package.json
test/SdkUnitTests.js

- Updated Travis-CI badge in README.md
-  Updated Get Form Data unit test.

Version 4.13.1 release

---

CHANGELOG.md
package.json

- Added support for version v2.1-21.2.02.00 of the DocuSign ESignature API.

Version v5.12.0 release

---

CHANGELOG.md
package.json

- Added support for version v2-21.2.02.00 of the DocuSign ESignature API.

Version v4.14.0 release

---

CHANGELOG.md
package.json
src/ApiClient.js
src/api/AccountsApi.js
src/api/EnvelopesApi.js
src/api/TemplatesApi.js
src/model/AccountIdentityVerificationWorkflow.js
src/model/AccountRoleSettings.js
src/model/AccountSettingsInformation.js
src/model/Brand.js
src/model/DelayedRouting.js
src/model/EnvelopeDocument.js
src/model/EnvelopeTemplate.js
src/model/EnvelopesInformation.js
src/model/InitialHere.js
src/model/NotaryRecipient.js
src/model/OfflineAttributes.js
src/model/ScheduledSending.js
src/model/UserSettingsInformation.js

- Added support for version v2.1-23.3.00.01 of the DocuSign ESignature API.

Version 6.4.0 release

---

CHANGELOG.md
package.json

- Rolled back the superagent-proxy package version from 3.0.0 to 2.0.0

Version 6.5.1 release

---

CHANGELOG.md
package.json

The `"token_scopes"` parameter has been moved from path parameters to query parameters for the above mentioned endpoint.
The body parameter `returnUrlRequest` has been changed to `envelopeViewRequest`.
`envelopeViewRequest` has the same properties as the previous `returnUrlRequest` but now includes additional `viewAccess` and `settings` properties, where settings is a complex object with several UI controls for the view experience.
The body parameter `returnUrlRequest` has been changed to `templateViewRequest`.
`templateViewRequest` has the same properties as the previous `returnUrlRequest` but now includes an additional `viewAccess` string.
- Updated existing models
- **Added fields:**
- `allowConnectEnvelopeRemovedEvent`
- `allowOrganizationBranding`
- …

Version 7.0.0 release

---

.swagger-codegen-ignore
CHANGELOG.md
package.json
src/ApiClient.js

Version 7.0.1 release

---

.swagger-codegen-ignore
CHANGELOG.md
README.md
package.json
src/ApiClient.js
test/SdkUnitTests.js
test/SdkUnitTestsWithCallback.js
test/helpers.js

- Resolved an issue with the PDF download logic that caused corrupted data.

Version 7.0.2 release

---

CHANGELOG.md
README.md
package.json
src/ApiClient.js
test/SdkUnitTests.js
test/SdkUnitTestsWithCallback.js

- Fixed issue with document downloads when `Content-Transfer-Encoding` is set to `base64`.

Version 8.0.1 release

---

CHANGELOG.md
README.md
package.json
src/ApiClient.js

- Added support for version v2.1-25.1.00.02 of the DocuSign ESignature API.

Version 8.1.0 release

---

CHANGELOG.md
README.md
package.json
src/ApiClient.js
src/api/AccountsApi.js
src/api/EnvelopesApi.js
src/api/TemplatesApi.js
src/model/AccountInformation.js
src/model/AccountSettingsInformation.js
src/model/Agent.js
src/model/Brand.js
src/model/DelayedRouting.js
src/model/DelegationInfo.js
src/model/Document.js
src/model/Editor.js
src/model/Envelope.js
src/model/EnvelopeDefinition.js
src/model/EnvelopeDocument.js
src/model/EnvelopeTemplate.js
src/model/Group.js
src/model/InPersonSigner.js
src/model/InitialHere.js
src/model/Intermediary.js
src/model/NotaryHost.js
src/model/OfflineAttributes.js
src/model/Participant.js
src/model/ScheduledSending.js
src/model/SealSign.js
src/model/TabAccountSettings.js
src/model/TemplateSummary.js

- Added support for version v2.1-25.2.00.00 of the DocuSign ESignature API.

Version 8.2.0 release

---

CHANGELOG.md
README.md
package.json
src/ApiClient.js
src/model/AccountSettingsInformation.js

- Added support for version v2.1-25.2.01.00 of the DocuSign ESignature API.

Version 8.3.0 release
